FROM maven:3.8.4-openjdk-17
ENV SENHA_POSTGRESQL postgres
ENV SENHA_TOKEN tokenpass

WORKDIR /app
WORKDIR /tmp

RUN git clone https://github.com/matheushajer/hackaton-pos-tech-fiap.git
WORKDIR /tmp/hackaton-pos-tech-fiap/usuarios

RUN mvn clean package -DskipTests

# Copia o jar para o diretorio /app
RUN cp target/*.jar /app


WORKDIR /app

# Define o comando para iniciar a API
CMD java -jar $(ls | grep .jar)


