FROM maven:3.8.4-openjdk-17
WORKDIR /app
WORKDIR /tmp

RUN git clone https://github.com/matheushajer/hackaton-pos-tech-fiap.git
WORKDIR /tmp/hackaton-pos-tech-fiap/gateway

RUN mvn clean package -DskipTests

# Copia o jar para o diretorio /app
RUN cp target/*.jar /app


# Expoe a porta 8082
EXPOSE 8082

WORKDIR /app

# Define o comando para iniciar a API
CMD java -jar $(ls | grep .jar)
